name: CI dÃ©butant

on:
  push:
    branches:
      - main

jobs:
  demo-ci:
    runs-on: ubuntu-latest

    steps:
      - name: RÃ©cupÃ©rer le code
        uses: actions/checkout@v4

      - name: Tests
        run: |
          echo "Tests en cours..."
          exit 0

      - name: Build
        run: echo "Build terminÃ© âœ…"

      - name: Fin
        run: echo "Pipeline CI/CD rÃ©ussi ğŸ‰"
